/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Robson' at '17/05/16 10:05' with Gradle 2.13
 *
 * @author Robson, @date 17/05/16 10:05
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
