FROM java:jre-alpine
MAINTAINER robsonoduarte


ADD target/docker-scala-0.1.0-jar-with-dependencies.jar /docker-scala-0.1.0-jar-with-dependencies.jar

CMD ["java", "-jar", "docker-scala-0.1.0-jar-with-dependencies.jar"]


